# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_api', '0004_auto_20171128_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='item',
            new_name='catalogo',
        ),
    ]
